# permissions for end users to edit podcontrollers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podcontroller-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: podcontroller
    app.kubernetes.io/part-of: podcontroller
    app.kubernetes.io/managed-by: kustomize
  name: podcontroller-editor-role
rules:
- apiGroups:
  - kubebin.com.my.domain
  resources:
  - podcontrollers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kubebin.com.my.domain
  resources:
  - podcontrollers/status
  verbs:
  - get
